# Generated by Django 4.2.4 on 2023-08-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='no_picture_user.jpg', upload_to='users'),
        ),
    ]
