# Generated by Django 4.2.5 on 2023-10-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_method_alter_recipe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.CharField(default='recipes/images/no_picture.jpg', max_length=200),
        ),
    ]
